# The RAGFlow team do not actively maintain docker-compose-gpu.yml, so use them at your own risk. 
# Pull requests to improve it are welcome.
include:
  - ./docker-compose-base.yml

services:
  ragflow:
    depends_on:
      mysql:
        condition: service_healthy
    image: ${RAGFLOW_IMAGE}
    container_name: ragflow-server
    ports:
      - ${SVR_HTTP_PORT}:9380
      - 80:80
      - 443:443
    volumes:
      - ./ragflow-logs:/ragflow/logs
      - ./nginx/ragflow.conf:/etc/nginx/conf.d/ragflow.conf
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    env_file: .env
    environment:
      - TZ=${TIMEZONE}
      - HF_ENDPOINT=${HF_ENDPOINT}
      - MACOS=${MACOS}
      - KNOWFLOW_API_URL=${KNOWFLOW_API_URL:-http://knowflow-backend:5000}
    networks:
      - ragflow
    restart: on-failure
    # https://docs.docker.com/engine/daemon/prometheus/#create-a-prometheus-configuration
    # If you're using Docker Desktop, the --add-host flag is optional. This flag makes sure that the host's internal IP gets exposed to the Prometheus container.
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]


  knowflow-backend:
    container_name: knowflow-backend
    image: zxwei/knowflow-server:v2.0.9
    build:
      context: ../knowflow
      dockerfile: Dockerfile
      target: backend
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "5000:5000"
    environment:
      - RAGFLOW_BASE_URL=${RAGFLOW_BASE_URL:-http://ragflow-server:9380}
      - DB_HOST=${DB_HOST:-mysql}
      - MYSQL_PORT=3306
      - MINIO_HOST=${MINIO_HOST:-minio}
      - MINIO_PORT=9000
      - ES_HOST=${ES_HOST:-es01}
      - ES_PORT=9200
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=6379
      - CORS_ALLOWED_ORIGINS=http://knowflow-frontend,http://localhost:3000
      - GOTENBERG_URL=http://knowflow-gotenberg:3000
      - MANAGEMENT_ADMIN_USERNAME=${MANAGEMENT_ADMIN_USERNAME:-admin}
      - MANAGEMENT_ADMIN_PASSWORD=${MANAGEMENT_ADMIN_PASSWORD:-12345678}
      - MANAGEMENT_JWT_SECRET=${MANAGEMENT_JWT_SECRET:-12345678}
      - TZ=${TIMEZONE:-UTC}
    volumes:
      - ../knowflow/server/services/config:/app/services/config:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - ragflow
    restart: on-failure
    depends_on:
      mysql:
        condition: service_healthy
      knowflow-gotenberg:
        condition: service_started


  knowflow-gotenberg:
    container_name: knowflow-gotenberg
    image: gotenberg/gotenberg:8
    ports:
      - "3000:3000"
    environment:
      - TZ=${TIMEZONE:-UTC}
    networks:
      - ragflow
    restart: on-failure